spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/demo
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                #use_sql_comments : true
        hibernate:
            ddl-auto: update

    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html

logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace


        #org.hibernate.SQL: debug
        #org.hibernate.type: SQL
